---
configs:
    use: 'office'
    office:
        unix: no
        ram: '8192'
        hdd_size_in_gb: 60
        swap_size_in_gb: 8
    home:
        unix: yes
        ram: '4096'
        hdd_size_in_gb: 20
        swap_size_in_gb: 8
