---

# set to yes if you create the VM with this ansible script
vagrant_setup: no

# Linux username
user_name: andy
# create a Linux password with mkpasswd: See Readme for usage
user_password: $6$buhLAvhwu/nM9Ixy$An.n76lRS5TvO1lO31Af3nnFyLU72cqBpDT8uof1nEIDTMDWaJdfUqhrsVHDYN8p3znftKsory44gDuEJO8mD0
# The XKB keyboard layout name: Sets the keyboard language (de: german, us: english)
keyboard_layout: de
# set the path to your .bashrc if you want it to be deployed. If not set or path is wrong, this will be skipped
src_bashrc: ~/.bashrc
# set the path to your private key if you want it to be deployed. If not set or path is wrong, this will be skipped
src_private_ssh_key: ~/.ssh/id_rsa
# set the path to your ssh config file if you want it to be deployed. If not set or path is wrong, this will be skipped
src_ssh_config: ~/.ssh/config

packages_to_install: [
  vim, nodejs, npm, git, git-flow, tree, docker.io, ruby2.3-dev, vagrant, virtualbox
]

ruby_gems_to_install: [
  berkshelf, kitchen-vagrant, kitchen-docker, knife-push
]
# choose `yes` or `no`if you want to have the chefDK to be installed or not
install_chef: yes
#chefdk_deb_url: "https://packages.chef.io/files/stable/chef/12.15.19/ubuntu/16.04/chef_12.15.19-1_amd64.deb"
chefdk_deb_url: "https://packages.chef.io/stable/ubuntu/12.04/chefdk_0.19.6-1_amd64.deb"
chefdk_deb_filename: /tmp/chefdk.deb
chefdk_deb_checksum: "sha256:e6e121bf1955c37f604a40c102ce1e797ed854ea1cbecb9ab380e4e342618fd2"

install_atom: no
atom_deb_url: "https://github.com/atom/atom/releases/download/v1.11.2/atom-amd64.deb"
atom_deb_filename: /tmp/atom.deb

install_visual_studio_code: yes
visual_studio_code_url: "https://go.microsoft.com/fwlink/?LinkID=760868"
visual_studio_code_deb_filename: /tmp/code.deb

# with gitlab_mainurl and workspaces, this playbook will automatically create workspace directories and
# clone some projects inside them.
# A workspace directory will be created to /home/<username>/<name> where the corresponding Git projects will be cloned into.
create_workspace: no
gitlab_mainurl: <gitlab-repo>
workspaces:
  - name: <workspace-1>
    git_group: <git-group-1>
    git_projects:
      - <git-project-1>
      - <git-project-2>
  - name: <workspace-2>
    git_group: <git-group-2>
    git_projects:
      - <git-project-1>
      - <git-project-2>
      - <git-project-3>
